apiVersion: v1
kind: Pod
metadata:
  name: readiness-app
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /ready
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3

---
apiVersion: v1
kind: Pod
metadata:
  name: tcp-readiness-app
spec:
  containers:
  - name: my-container
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      failureThreshold: 3

---
apiVersion: v1
kind: Pod
metadata:
  name: exec-readiness-app
spec:
  containers:
  - name: my-container
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 10; touch /tmp/ready; sleep 60; rm -f /tmp/ready
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 10
