apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-django-app
  namespace: test-ns
  labels:
    app: test-django-app
spec:
  selector:
    matchLabels:
      app: test-django-app
  replicas: 5
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-django-app
    spec:
      containers:
      - name: test-django-app
        image: nginx:latest  # Ensure this image is in the correct registry
        imagePullPolicy: Always  # Force Kubernetes to always pull the latest image
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 80
