apiVersion: apps/v1
kind: Deployment
metadata:
  name: two-tier-app
spec:
  selector:
    matchLabels:
      app: two-tier-app
  template:
    metadata:
      labels:
        app: two-tier-app
    spec:
      containers:
      - name: two-tier-app
        image: /akshay196/two-tier-app:tagname
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: two-tier-app-service
spec:
  selector:
    app: two-tier-app
  ports:
  - port: 80
    targetPort: 8080

