apiVersion: v1
kind: Secret
metadata:
  name: docker-login
type: Opaque
data:
  DOCKER_SERVER: https://index.docker.io/v1/ 
  DOCKER_USERNAME: YWtzaGF5MTk2
  DOCKER_PASSWORD: OmRja3JfcGF0X016SkRDZnFzX2kzcDZ4UUFTT3RWSlFqRkhvUQ==
  DOCKER_EMAIL: jadhavakshay0504@gmail.com 